title = "SLNVim TOML Example"
sln_path = "Test.sln"

[[tasks]]
name = "Build Debug"
cmd = "dotnet build -c Debug"

[[tasks]]
name = "Build Release"
cmd = "dotnet build -c Release"

[[projects]]
id = "{45DAFB73-3431-4C46-95FE-1FBC6E6110DE}"

[[startup_configs]]
name = "Debug My App"
projects = ["{45DAFB73-3431-4C46-95FE-1FBC6E6110DE}", "{AE2F1A24-7F92-4DC8-90A6-B20EF2CA4CE3}"]
pre_run_tasks = ["Build Debug"]
